AdminUser.create!(email: 'admin@admin.com', password: 'password', password_confirmation: 'password')

City.create!([
  {title: "수원시 갑"},
  {title: "수원시 을"},
  {title: "수원시 병"},
  {title: "수원시 정"},
  {title: "수원시 무"},
  {title: "성남시 수정구"},
  {title: "성남시 중원구"},
  {title: "성남시 분당구 갑"},
  {title: "성남시 분당구 을"},
  {title: "의정부시 갑"},
  {title: "의정부시 을"},
  {title: "안양시 만안구"},
  {title: "안양시 동안구 갑"},
  {title: "안양시 동안구 을"},
  {title: "부천시 원미구 갑"},
  {title: "부천시 원미구 을"},
  {title: "부천시 소사구"},
  {title: "부천시 오정구"},
  {title: "광명시 갑"},
  {title: "광명시 을"},
  {title: "평택시 갑"},
  {title: "평택시 을"},
  {title: "동두천시 연천군"},
  {title: "안산시 상록구 갑"},
  {title: "안산시 상록구 을"},
  {title: "안산시 단원구 갑"},
  {title: "안산시 단원구 을"},
  {title: "고양시 갑"},
  {title: "고양시 을"},
  {title: "고양시 병"},
  {title: "고양시 정"},
  {title: "의왕시-과천시"},
  {title: "구리시"},
  {title: "남양주시 갑"},
  {title: "남양주시 을"},
  {title: "남양주시 병"},
  {title: "오산시"},
  {title: "시흥시 갑"},
  {title: "시흥시 을"},
  {title: "군포시 갑"},
  {title: "군포시 을"},
  {title: "하남시"},
  {title: "용인시 갑"},
  {title: "용인시 을"},
  {title: "용인시 병"},
  {title: "용인시 정"},
  {title: "파주시 갑"},
  {title: "파주시 을"},
  {title: "이천시"},
  {title: "안성시"},
  {title: "김포시 갑"},
  {title: "김포시 을"},
  {title: "화성시 갑"},
  {title: "화성시 을"},
  {title: "화성시 병"},
  {title: "광주시 갑"},
  {title: "광주시 을"},
  {title: "양주시"},
  {title: "포천시-가평군"},
  {title: "여주시-양평군"}
])
District.create!([
  {title: "수원시 장안구 파장동", city_id: 1},
  {title: "수원시 장안구 정자1동", city_id: 1},
  {title: "수원시 장안구 정자2동", city_id: 1},
  {title: "수원시 장안구 정자3동", city_id: 1},
  {title: "수원시 장안구 영화동", city_id: 1},
  {title: "수원시 장안구 송죽동", city_id: 1},
  {title: "수원시 장안구 조원1동", city_id: 1},
  {title: "수원시 장안구 조원2동", city_id: 1},
  {title: "수원시 장안구 연무동", city_id: 1},
  {title: "수원시 장안구 율천동", city_id: 2},
  {title: "수원시 권선구 평동", city_id: 2},
  {title: "수원시 권선구 서둔동", city_id: 2},
  {title: "수원시 권선구 구운동", city_id: 2},
  {title: "수원시 권선구 금곡동", city_id: 2},
  {title: "수원시 권선구 호매실동", city_id: 2},
  {title: "수원시 권선구 입북동", city_id: 2},
  {title: "수원시 팔달구", city_id: 3},
  {title: "수원시 영통구 매탄1동", city_id: 4},
  {title: "수원시 영통구 매탄2동", city_id: 4},
  {title: "수원시 영통구 매탄3동", city_id: 4},
  {title: "수원시 영통구 매탄4동", city_id: 4},
  {title: "수원시 영통구 원천동", city_id: 4},
  {title: "수원시 영통구 영통1동", city_id: 4},
  {title: "수원시 영통구 광교1동", city_id: 4},
  {title: "수원시 영통구 광교2동", city_id: 4},
  {title: "수원시 권선구 세류1동", city_id: 5},
  {title: "수원시 권선구 세류2동", city_id: 5},
  {title: "수원시 권선구 세류 3동", city_id: 5},
  {title: "수원시 권선구 권선1동", city_id: 5},
  {title: "수원시 권선구 권선2동", city_id: 5},
  {title: "수원시 권선구 곡선동", city_id: 5},
  {title: "수원시 영통구 영통2동", city_id: 5},
  {title: "수원시 영통구 태장동", city_id: 5},
  {title: "성남시 수정구", city_id: 6},
  {title: "성남시 중원구", city_id: 7},
  {title: "성남시 분당구 서현1동", city_id: 8},
  {title: "성남시 분당구 서현2동", city_id: 8},
  {title: "성남시 분당구 이매1동", city_id: 8},
  {title: "성남시 분당구 이매2동", city_id: 8},
  {title: "성남시 분당구 야탑1동", city_id: 8},
  {title: "성남시 분당구 야탑2동", city_id: 8},
  {title: "성남시 분당구 야탑3동", city_id: 8},
  {title: "성남시 분당구 판교동", city_id: 8},
  {title: "성남시 분당구 삼평동", city_id: 8},
  {title: "성남시 분당구 백현동", city_id: 8},
  {title: "성남시 분당구 운중동", city_id: 8},
  {title: "성남시 분당구 분당동", city_id: 9},
  {title: "성남시 분당구 수내1동", city_id: 9},
  {title: "성남시 분당구 수내2동", city_id: 9},
  {title: "성남시 분당구 수내3동", city_id: 9},
  {title: "성남시 분당구 정자동", city_id: 9},
  {title: "성남시 분당구 정자1동", city_id: 9},
  {title: "성남시 분당구 정자2동", city_id: 9},
  {title: "성남시 분당구 정자3동", city_id: 9},
  {title: "성남시 분당구 금곡동", city_id: 9},
  {title: "성남시 분당구 구미동", city_id: 9},
  {title: "성남시 분당구 구미1동", city_id: 9},
  {title: "의정부시 의정부1동", city_id: 10},
  {title: "의정부시 의정부2동", city_id: 10},
  {title: "의정부시 의정부3동", city_id: 10},
  {title: "의정부시 호원1동", city_id: 10},
  {title: "의정부시 호원2동", city_id: 10},
  {title: "의정부시 가능1동", city_id: 10},
  {title: "의정부시 흥선동", city_id: 10},
  {title: "의정부시 녹양동", city_id: 10},
  {title: "의정부시 장암동", city_id: 11},
  {title: "의정부시 신곡1동", city_id: 11},
  {title: "의정부시 신곡2동", city_id: 11},
  {title: "의정부시 송산1동", city_id: 11},
  {title: "의정부시 송산2동", city_id: 11},
  {title: "의정부시 자금동", city_id: 11},
  {title: "안양시 만안구", city_id: 12},
  {title: "안양시 동안구 비산1동", city_id: 13},
  {title: "안양시 동안구 비산2동", city_id: 13},
  {title: "안양시 동안구 비산3동", city_id: 13},
  {title: "안양시 동안구 부흥동", city_id: 13},
  {title: "안양시 동안구 달안동", city_id: 13},
  {title: "안양시 동안구 관양1동", city_id: 13},
  {title: "안양시 동안구 관양2동", city_id: 13},
  {title: "안양시 동안구 부림동", city_id: 13},
  {title: "안양시 동안구 평촌동", city_id: 14},
  {title: "안양시 동안구 평안동", city_id: 14},
  {title: "안양시 동안구 귀인동", city_id: 14},
  {title: "안양시 동안구 호계1동", city_id: 14},
  {title: "안양시 동안구 호계2동", city_id: 14},
  {title: "안양시 동안구 호계3동", city_id: 14},
  {title: "안양시 동안구 범계동", city_id: 14},
  {title: "안양시 동안구 신촌동", city_id: 14},
  {title: "안양시 동안구 갈산동", city_id: 14},
  {title: "부천시 심곡동", city_id: 15},
  {title: "부천시 원미동", city_id: 15},
  {title: "부천시 소사동", city_id: 15},
  {title: "부천시 역곡1동", city_id: 15},
  {title: "부천시 역곡2동", city_id: 15},
  {title: "부천시 춘의동", city_id: 15},
  {title: "부천시 원미구 도당동", city_id: 15},
  {title: "부천시 중동", city_id: 16},
  {title: "부천시 약대동", city_id: 16},
  {title: "부천시 상동", city_id: 16},
  {title: "부천시 심곡본동", city_id: 17},
  {title: "부천시 송내동", city_id: 17},
  {title: "부천시 소사본동", city_id: 17},
  {title: "부천시 범박동", city_id: 17},
  {title: "부천시 괴안동", city_id: 17},
  {title: "부천시 역곡3동", city_id: 17},
  {title: "부천시 성곡동", city_id: 18},
  {title: "부천시 고강본동", city_id: 18},
  {title: "부천시 고강동", city_id: 18},
  {title: "부천시 원종동", city_id: 18},
  {title: "부천시 오정동", city_id: 18},
  {title: "부천시 신흥동", city_id: 18},
  {title: "광명시 광명동", city_id: 19},
  {title: "광명시 철산1동", city_id: 19},
  {title: "광명시 철산2동", city_id: 19},
  {title: "광명시 철산4동", city_id: 19},
  {title: "광명시 철산3동", city_id: 20},
  {title: "광명시 하안동", city_id: 20},
  {title: "광명시 소하동", city_id: 20},
  {title: "광명시 학온동", city_id: 20},
  {title: "평택시 진위면", city_id: 21},
  {title: "평택시 서탄면", city_id: 21},
  {title: "평택시 중앙동", city_id: 21},
  {title: "평택시 서정동", city_id: 21},
  {title: "평택시 송탄동", city_id: 21},
  {title: "평택시 지산동", city_id: 21},
  {title: "평택시 송북동", city_id: 21},
  {title: "평택시 신장1동", city_id: 21},
  {title: "평택시 신장2동", city_id: 21},
  {title: "평택시 통복동", city_id: 21},
  {title: "평택시 세교동", city_id: 21},
  {title: "평택시 팽성읍", city_id: 22},
  {title: "평택시 안중읍", city_id: 22},
  {title: "평택시 포승읍", city_id: 22},
  {title: "평택시 청북읍", city_id: 22},
  {title: "평택시 고덕면", city_id: 22},
  {title: "평택시 오성면", city_id: 22},
  {title: "평택시 현덕면", city_id: 22},
  {title: "평택시 신평동", city_id: 22},
  {title: "평택시 원평동", city_id: 22},
  {title: "평택시 비전동", city_id: 22},
  {title: "동두천시", city_id: 23},
  {title: "연천군", city_id: 23},
  {title: "안산시 상록구 사동", city_id: 24},
  {title: "안산시 상록구 사이동", city_id: 24},
  {title: "안산시 상록구 해양동", city_id: 24},
  {title: "안산시 상록구 본오동", city_id: 24},
  {title: "안산시 상록구 반월동", city_id: 24},
  {title: "안산시 상록구 일동", city_id: 25},
  {title: "안산시 상록구 이동", city_id: 25},
  {title: "안산시 상록구 부곡동", city_id: 25},
  {title: "안산시 상록구 월피동", city_id: 25},
  {title: "안산시 상록구 성포동", city_id: 25},
  {title: "안산시 상록구 안산동", city_id: 25},
  {title: "안산시 단원구 와동", city_id: 26},
  {title: "안산시 단원구 원곡본동", city_id: 26},
  {title: "안산시 단원구 원곡동", city_id: 26},
  {title: "안산시 단원구 선부동", city_id: 26},
  {title: "안산시 단원구 고잔동", city_id: 27},
  {title: "안산시 단원구 호수동", city_id: 27},
  {title: "안산시 단원구 초지동", city_id: 27},
  {title: "안산시 단원구 초지동", city_id: 27},
  {title: "안산시 단원구 대부동", city_id: 27},
  {title: "고양시 덕양구 주교동", city_id: 28},
  {title: "고양시 덕양구 원신동", city_id: 28},
  {title: "고양시 덕양구 흥도동", city_id: 28},
  {title: "고양시 덕양구 성사동", city_id: 28},
  {title: "고양시 덕양구 고양동", city_id: 28},
  {title: "고양시 덕양구 관산동", city_id: 28},
  {title: "고양시 덕양구 화정동", city_id: 28},
  {title: "고양시 일산동구 식사동", city_id: 28},
  {title: "고양시 덕양구 효자동", city_id: 29},
  {title: "고양시 덕양구 신도동", city_id: 29},
  {title: "고양시 덕양구 창릉동", city_id: 29},
  {title: "고양시 덕양구 능곡동", city_id: 29},
  {title: "고양시 덕양구 행주동", city_id: 29},
  {title: "고양시 덕양구 행신동", city_id: 29},
  {title: "고양시 덕양구 화전동", city_id: 29},
  {title: "고양시 덕양구 대덕동", city_id: 29},
  {title: "고양시 일산동구 중산동", city_id: 30},
  {title: "고양시 일산동구 정발산동", city_id: 30},
  {title: "고양시 일산동구 풍산동", city_id: 30},
  {title: "고양시 일산동구 백석동", city_id: 30},
  {title: "고양시 일산동구 마두동", city_id: 30},
  {title: "고양시 일산동구 장항동", city_id: 30},
  {title: "고양시 일산동구 고봉동", city_id: 30},
  {title: "고양시 일산서구 일산2동", city_id: 30},
  {title: "고양시 일산서구 일산1동", city_id: 31},
  {title: "고양시 일산서구 일산3동", city_id: 31},
  {title: "고양시 일산서구 탄현동", city_id: 31},
  {title: "고양시 일산서구 주엽동", city_id: 31},
  {title: "고양시 일산서구 대화동", city_id: 31},
  {title: "고양시 일산서구 송포동", city_id: 31},
  {title: "고양시 일산서구 송산동", city_id: 31},
  {title: "과천시", city_id: 32},
  {title: "의왕시", city_id: 32},
  {title: "구리시", city_id: 33},
  {title: "남양주시 화도읍", city_id: 34},
  {title: "남양주시 수동면", city_id: 34},
  {title: "남양주시 호평동", city_id: 34},
  {title: "남양주시 평내동", city_id: 34},
  {title: "남양주시 진전읍", city_id: 35},
  {title: "남양주시 오남읍", city_id: 35},
  {title: "남양주시 별내면", city_id: 35},
  {title: "남양주시 별내동", city_id: 35},
  {title: "남양주시 와부읍", city_id: 36},
  {title: "남양주시 진건읍", city_id: 36},
  {title: "남양주시 조안면", city_id: 36},
  {title: "남양주시 퇴계원면", city_id: 36},
  {title: "남양주시 금곡동", city_id: 36},
  {title: "남양주시 양정동", city_id: 36},
  {title: "남양주시 다산동", city_id: 36},
  {title: "오산시", city_id: 37},
  {title: "시흥시 대야동", city_id: 38},
  {title: "시흥시 신천동", city_id: 38},
  {title: "시흥시 신현동", city_id: 38},
  {title: "시흥시 은행동", city_id: 38},
  {title: "시흥시 매화동", city_id: 38},
  {title: "시흥시 목감동", city_id: 38},
  {title: "시흥시 과림동", city_id: 38},
  {title: "시흥시 연성동", city_id: 38},
  {title: "시흥시 장곡동", city_id: 38},
  {title: "시흥시 능곡동", city_id: 38},
  {title: "시흥시 군자동", city_id: 39},
  {title: "시흥시 월곶동", city_id: 39},
  {title: "시흥시 정왕본동", city_id: 39},
  {title: "시흥시 정왕동", city_id: 39},
  {title: "군포시 군포동", city_id: 40},
  {title: "군포시 산본1동", city_id: 40},
  {title: "군포시 금정동", city_id: 40},
  {title: "군포시 대야동", city_id: 40},
  {title: "군포시 산본2동", city_id: 41},
  {title: "군포시 재궁동", city_id: 41},
  {title: "군포시 오금동", city_id: 41},
  {title: "군포시 수리동", city_id: 41},
  {title: "군포시 궁내동", city_id: 41},
  {title: "군포시 광정동", city_id: 41},
  {title: "하남시", city_id: 42},
  {title: "용인시 처인구", city_id: 43},
  {title: "용인시 기흥구 신갈동", city_id: 44},
  {title: "용인시 기흥구 영덕동", city_id: 44},
  {title: "용인시 기흥구 구갈동", city_id: 44},
  {title: "용인시 기흥구 상갈동", city_id: 44},
  {title: "용인시 기흥구 기흥동", city_id: 44},
  {title: "용인시 기흥구 서농동", city_id: 44},
  {title: "용인시 기흥구 상하동", city_id: 44},
  {title: "용인시 수지구 풍덕천동", city_id: 45},
  {title: "용인시 수지구 신봉동", city_id: 45},
  {title: "용인시 수지구 동천동", city_id: 45},
  {title: "용인시 수지구 상현동", city_id: 45},
  {title: "용인시 수지구 성복동", city_id: 45},
  {title: "용인시 기흥구 구성동", city_id: 46},
  {title: "용인시 기흥구 마북동", city_id: 46},
  {title: "용인시 기흥구 동백동", city_id: 46},
  {title: "용인시 기흥구 보정동", city_id: 46},
  {title: "용인시  수지구 죽전동", city_id: 46},
  {title: "파주시 조리읍", city_id: 47},
  {title: "파주시 광탄면", city_id: 47},
  {title: "파주시 탄현면", city_id: 47},
  {title: "파주시 교하동", city_id: 47},
  {title: "파주시 운정동", city_id: 47},
  {title: "파주시 문산읍", city_id: 48},
  {title: "파주시 법원읍", city_id: 48},
  {title: "파주시 파주읍", city_id: 48},
  {title: "파주시 월롱면", city_id: 48},
  {title: "파주시 적성면", city_id: 48},
  {title: "파주시 파평면", city_id: 48},
  {title: "파주시 장단출장소", city_id: 48},
  {title: "파주시 금촌동", city_id: 48},
  {title: "이천시", city_id: 49},
  {title: "안성시", city_id: 50},
  {title: "김포시 고촌읍", city_id: 51},
  {title: "김포시 김포본동", city_id: 51},
  {title: "김포시 사우동", city_id: 51},
  {title: "김포시 풍무동", city_id: 51},
  {title: "김포시 장기동", city_id: 51},
  {title: "김포시 통진읍", city_id: 52},
  {title: "김포시 양촌읍", city_id: 52},
  {title: "김포시 대곶면", city_id: 52},
  {title: "김포시 월곶면", city_id: 52},
  {title: "김포시 하성면", city_id: 52},
  {title: "김포시 장기본동", city_id: 52},
  {title: "김포시 장기본동", city_id: 52},
  {title: "김포시 구래동", city_id: 52},
  {title: "김포시 운양동", city_id: 52},
  {title: "화성시 우정읍", city_id: 53},
  {title: "화성시 향남읍", city_id: 53},
  {title: "화성시 남양읍", city_id: 53},
  {title: "화서시 매송면", city_id: 53},
  {title: "화성시 매송면", city_id: 53},
  {title: "화성시 비봉면", city_id: 53},
  {title: "화성시 마도면", city_id: 53},
  {title: "화성시 송산면", city_id: 53},
  {title: "화성시 서신면", city_id: 53},
  {title: "화성시 팔탄면", city_id: 53},
  {title: "화성시 장안면", city_id: 53},
  {title: "화성시 양감면", city_id: 53},
  {title: "화성시 정남면", city_id: 53},
  {title: "화성시 동탄면", city_id: 54},
  {title: "화성시 동탄동", city_id: 54},
  {title: "화성시 봉담읍", city_id: 55},
  {title: "화성시 진안동", city_id: 55},
  {title: "화성시 병점동", city_id: 55},
  {title: "화성시 반월동", city_id: 55},
  {title: "화성시 기배동", city_id: 55},
  {title: "화성시 화산동", city_id: 55},
  {title: "광주시 퇴촌면", city_id: 56},
  {title: "광주시 남종면", city_id: 56},
  {title: "광주시 남한산성면", city_id: 56},
  {title: "광주시 경안동", city_id: 56},
  {title: "광주시 송정동", city_id: 56},
  {title: "광주시 광남동", city_id: 56},
  {title: "광주시 오포읍", city_id: 57},
  {title: "광주시 초월읍", city_id: 57},
  {title: "광주시 곤지암읍", city_id: 57},
  {title: "광주시 도척면", city_id: 57},
  {title: "양주시", city_id: 58},
  {title: "포천시", city_id: 59},
  {title: "가평군", city_id: 59},
  {title: "여주시", city_id: 60},
  {title: "양평군", city_id: 60}
])
