AdminUser.create!(email: 'admin@admin.com', password: 'password', password_confirmation: 'password')
City.create!([
  {title: "수원시 갑"},
  {title: "수원시 을"},
  {title: "수원시 병"},
  {title: "수원시 정"},
  {title: "수원시 무"},
  {title: "성남시 수정구"},
  {title: "성남시 중원구"},
  {title: "성남시 분당구 갑"},
  {title: "성남시 분당구 을"},
  {title: "의정부시 갑"},
  {title: "의정부시 을"},
  {title: "안양시 만안구"},
  {title: "안양시 동안구 갑"},
  {title: "안양시 동안구 을"},
  {title: "부천시 원미구 갑"},
  {title: "부천시 원미구 을"},
  {title: "부천시 소사구"},
  {title: "부천시 오정구"},
  {title: "광명시 갑"},
  {title: "광명시 을"},
  {title: "평택시 갑"},
  {title: "평택시 을"},
  {title: "동두천시 연천군"},
  {title: "안산시 상록구 갑"},
  {title: "안산시 상록구 을"},
  {title: "안산시 단원구 갑"},
  {title: "안산시 단원구 을"},
  {title: "고양시 갑"},
  {title: "고양시 을"},
  {title: "고양시 병"},
  {title: "고양시 정"},
  {title: "의왕시-과천시"},
  {title: "구리시"},
  {title: "남양주시 갑"},
  {title: "남양주시 을"},
  {title: "남양주시 병"},
  {title: "오산시"},
  {title: "시흥시 갑"},
  {title: "시흥시 을"},
  {title: "군포시 갑"},
  {title: "군포시 을"},
  {title: "하남시"},
  {title: "용인시 갑"},
  {title: "용인시 을"},
  {title: "용인시 병"},
  {title: "용인시 정"},
  {title: "파주시 갑"},
  {title: "파주시 을"},
  {title: "이천시"},
  {title: "안성시"},
  {title: "김포시 갑"},
  {title: "김포시 을"},
  {title: "화성시 갑"},
  {title: "화성시 을"},
  {title: "화성시 병"},
  {title: "광주시 갑"},
  {title: "광주시 을"},
  {title: "양주시"},
  {title: "포천시-가평군"},
  {title: "여주시-양평군"}
])

Post.create!([
  {title: "테스트", content: "테스트"},
  {title: "2018년 2월 일정", content: "공지사항으로 모두에게 공개되는 2018년 2월 이후 포럼 일정입니다."}
])
District.create!([
  {title: "수원시 장안구 파장동", city_id: 1},
  {title: "수원시 장안구 정자1동", city_id: 1},
  {title: "수원시 장안구 정자2동", city_id: 1},
  {title: "수원시 장안구 정자3동", city_id: 1},
  {title: "수원시 장안구 영화동", city_id: 1},
  {title: "수원시 장안구 송죽동", city_id: 1},
  {title: "수원시 장안구 조원1동", city_id: 1},
  {title: "수원시 장안구 조원2동", city_id: 1},
  {title: "수원시 장안구 연무동", city_id: 1},
  {title: "수원시 장안구 율천동", city_id: 2},
  {title: "수원시 권선구 평동", city_id: 2},
  {title: "수원시 권선구 서둔동", city_id: 2},
  {title: "수원시 권선구 구운동", city_id: 2},
  {title: "수원시 권선구 금곡동", city_id: 2},
  {title: "수원시 권선구 호매실동", city_id: 2},
  {title: "수원시 권선구 입북동", city_id: 2},
  {title: "수원시 팔달구", city_id: 3},
  {title: "수원시 영통구 매탄1동", city_id: 4},
  {title: "수원시 영통구 매탄2동", city_id: 4},
  {title: "수원시 영통구 매탄3동", city_id: 4},
  {title: "수원시 영통구 매탄4동", city_id: 4},
  {title: "수원시 영통구 원천동", city_id: 4},
  {title: "수원시 영통구 영통1동", city_id: 4},
  {title: "수원시 영통구 광교1동", city_id: 4},
  {title: "수원시 영통구 광교2동", city_id: 4},
  {title: "수원시 권선구 세류1동", city_id: 5},
  {title: "수원시 권선구 세류2동", city_id: 5},
  {title: "수원시 권선구 세류 3동", city_id: 5},
  {title: "수원시 권선구 권선1동", city_id: 5},
  {title: "수원시 권선구 권선2동", city_id: 5},
  {title: "수원시 권선구 곡선동", city_id: 5},
  {title: "수원시 영통구 영통2동", city_id: 5},
  {title: "수원시 영통구 태장동", city_id: 5},
  {title: "성남시 수정구", city_id: 6},
  {title: "성남시 중원구", city_id: 7},
  {title: "성남시 분당구 서현1동", city_id: 8},
  {title: "성남시 분당구 서현2동", city_id: 8},
  {title: "성남시 분당구 이매1동", city_id: 8},
  {title: "성남시 분당구 이매2동", city_id: 8},
  {title: "성남시 분당구 야탑1동", city_id: 8},
  {title: "성남시 분당구 야탑2동", city_id: 8},
  {title: "성남시 분당구 야탑3동", city_id: 8},
  {title: "성남시 분당구 판교동", city_id: 8},
  {title: "성남시 분당구 삼평동", city_id: 8},
  {title: "성남시 분당구 백현동", city_id: 8},
  {title: "성남시 분당구 운중동", city_id: 8},
  {title: "성남시 분당구 분당동", city_id: 9},
  {title: "성남시 분당구 수내1동", city_id: 9},
  {title: "성남시 분당구 수내2동", city_id: 9},
  {title: "성남시 분당구 수내3동", city_id: 9},
  {title: "성남시 분당구 정자동", city_id: 9},
  {title: "성남시 분당구 정자1동", city_id: 9},
  {title: "성남시 분당구 정자2동", city_id: 9},
  {title: "성남시 분당구 정자3동", city_id: 9},
  {title: "성남시 분당구 금곡동", city_id: 9},
  {title: "성남시 분당구 구미동", city_id: 9},
  {title: "성남시 분당구 구미1동", city_id: 9},
  {title: "의정부시 의정부1동", city_id: 10},
  {title: "의정부시 의정부2동", city_id: 10},
  {title: "의정부시 의정부3동", city_id: 10},
  {title: "의정부시 호원1동", city_id: 10},
  {title: "의정부시 호원2동", city_id: 10},
  {title: "의정부시 가능1동", city_id: 10},
  {title: "의정부시 흥선동", city_id: 10},
  {title: "의정부시 녹양동", city_id: 10},
  {title: "의정부시 장암동", city_id: 11},
  {title: "의정부시 신곡1동", city_id: 11},
  {title: "의정부시 신곡2동", city_id: 11},
  {title: "의정부시 송산1동", city_id: 11},
  {title: "의정부시 송산2동", city_id: 11},
  {title: "의정부시 자금동", city_id: 11},
  {title: "안양시 만안구", city_id: 12},
  {title: "안양시 동안구 비산1동", city_id: 13},
  {title: "안양시 동안구 비산2동", city_id: 13},
  {title: "안양시 동안구 비산3동", city_id: 13},
  {title: "안양시 동안구 부흥동", city_id: 13},
  {title: "안양시 동안구 달안동", city_id: 13},
  {title: "안양시 동안구 관양1동", city_id: 13},
  {title: "안양시 동안구 관양2동", city_id: 13},
  {title: "안양시 동안구 부림동", city_id: 13},
  {title: "안양시 동안구 평촌동", city_id: 14},
  {title: "안양시 동안구 평안동", city_id: 14},
  {title: "안양시 동안구 귀인동", city_id: 14},
  {title: "안양시 동안구 호계1동", city_id: 14},
  {title: "안양시 동안구 호계2동", city_id: 14},
  {title: "안양시 동안구 호계3동", city_id: 14},
  {title: "안양시 동안구 범계동", city_id: 14},
  {title: "안양시 동안구 신촌동", city_id: 14},
  {title: "안양시 동안구 갈산동", city_id: 14},
  {title: "부천시 심곡동", city_id: 15},
  {title: "부천시 원미동", city_id: 15},
  {title: "부천시 소사동", city_id: 15},
  {title: "부천시 역곡1동", city_id: 15},
  {title: "부천시 역곡2동", city_id: 15},
  {title: "부천시 춘의동", city_id: 15},
  {title: "부천시 원미구 도당동", city_id: 15},
  {title: "부천시 중동", city_id: 16},
  {title: "부천시 약대동", city_id: 16},
  {title: "부천시 상동", city_id: 16},
  {title: "부천시 심곡본동", city_id: 17},
  {title: "부천시 송내동", city_id: 17},
  {title: "부천시 소사본동", city_id: 17},
  {title: "부천시 범박동", city_id: 17},
  {title: "부천시 괴안동", city_id: 17},
  {title: "부천시 역곡3동", city_id: 17},
  {title: "부천시 성곡동", city_id: 18},
  {title: "부천시 고강본동", city_id: 18},
  {title: "부천시 고강동", city_id: 18},
  {title: "부천시 원종동", city_id: 18},
  {title: "부천시 오정동", city_id: 18},
  {title: "부천시 신흥동", city_id: 18},
  {title: "광명시 광명동", city_id: 19},
  {title: "광명시 철산1동", city_id: 19},
  {title: "광명시 철산2동", city_id: 19},
  {title: "광명시 철산4동", city_id: 19},
  {title: "광명시 철산3동", city_id: 20},
  {title: "광명시 하안동", city_id: 20},
  {title: "광명시 소하동", city_id: 20},
  {title: "광명시 학온동", city_id: 20},
  {title: "평택시 진위면", city_id: 21},
  {title: "평택시 서탄면", city_id: 21},
  {title: "평택시 중앙동", city_id: 21},
  {title: "평택시 서정동", city_id: 21},
  {title: "평택시 송탄동", city_id: 21},
  {title: "평택시 지산동", city_id: 21},
  {title: "평택시 송북동", city_id: 21},
  {title: "평택시 신장1동", city_id: 21},
  {title: "평택시 신장2동", city_id: 21},
  {title: "평택시 통복동", city_id: 21},
  {title: "평택시 세교동", city_id: 21},
  {title: "평택시 팽성읍", city_id: 22},
  {title: "평택시 안중읍", city_id: 22},
  {title: "평택시 포승읍", city_id: 22},
  {title: "평택시 청북읍", city_id: 22},
  {title: "평택시 고덕면", city_id: 22},
  {title: "평택시 오성면", city_id: 22},
  {title: "평택시 현덕면", city_id: 22},
  {title: "평택시 신평동", city_id: 22},
  {title: "평택시 원평동", city_id: 22},
  {title: "평택시 비전동", city_id: 22},
  {title: "동두천시", city_id: 23},
  {title: "연천군", city_id: 23},
  {title: "안산시 상록구 사동", city_id: 24},
  {title: "안산시 상록구 사이동", city_id: 24},
  {title: "안산시 상록구 해양동", city_id: 24},
  {title: "안산시 상록구 본오동", city_id: 24},
  {title: "안산시 상록구 반월동", city_id: 24},
  {title: "안산시 상록구 일동", city_id: 25},
  {title: "안산시 상록구 이동", city_id: 25},
  {title: "안산시 상록구 부곡동", city_id: 25},
  {title: "안산시 상록구 월피동", city_id: 25},
  {title: "안산시 상록구 성포동", city_id: 25},
  {title: "안산시 상록구 안산동", city_id: 25},
  {title: "안산시 단원구 와동", city_id: 26},
  {title: "안산시 단원구 원곡본동", city_id: 26},
  {title: "안산시 단원구 원곡동", city_id: 26},
  {title: "안산시 단원구 선부동", city_id: 26},
  {title: "안산시 단원구 고잔동", city_id: 27},
  {title: "안산시 단원구 호수동", city_id: 27},
  {title: "안산시 단원구 초지동", city_id: 27},
  {title: "안산시 단원구 초지동", city_id: 27},
  {title: "안산시 단원구 대부동", city_id: 27},
  {title: "고양시 덕양구 주교동", city_id: 28},
  {title: "고양시 덕양구 원신동", city_id: 28},
  {title: "고양시 덕양구 흥도동", city_id: 28},
  {title: "고양시 덕양구 성사동", city_id: 28},
  {title: "고양시 덕양구 고양동", city_id: 28},
  {title: "고양시 덕양구 관산동", city_id: 28},
  {title: "고양시 덕양구 화정동", city_id: 28},
  {title: "고양시 일산동구 식사동", city_id: 28},
  {title: "고양시 덕양구 효자동", city_id: 29},
  {title: "고양시 덕양구 신도동", city_id: 29},
  {title: "고양시 덕양구 창릉동", city_id: 29},
  {title: "고양시 덕양구 능곡동", city_id: 29},
  {title: "고양시 덕양구 행주동", city_id: 29},
  {title: "고양시 덕양구 행신동", city_id: 29},
  {title: "고양시 덕양구 화전동", city_id: 29},
  {title: "고양시 덕양구 대덕동", city_id: 29},
  {title: "고양시 일산동구 중산동", city_id: 30},
  {title: "고양시 일산동구 정발산동", city_id: 30},
  {title: "고양시 일산동구 풍산동", city_id: 30},
  {title: "고양시 일산동구 백석동", city_id: 30},
  {title: "고양시 일산동구 마두동", city_id: 30},
  {title: "고양시 일산동구 장항동", city_id: 30},
  {title: "고양시 일산동구 고봉동", city_id: 30},
  {title: "고양시 일산서구 일산2동", city_id: 30},
  {title: "고양시 일산서구 일산1동", city_id: 31},
  {title: "고양시 일산서구 일산3동", city_id: 31},
  {title: "고양시 일산서구 탄현동", city_id: 31},
  {title: "고양시 일산서구 주엽동", city_id: 31},
  {title: "고양시 일산서구 대화동", city_id: 31},
  {title: "고양시 일산서구 송포동", city_id: 31},
  {title: "고양시 일산서구 송산동", city_id: 31},
  {title: "과천시", city_id: 32},
  {title: "의왕시", city_id: 32},
  {title: "구리시", city_id: 33},
  {title: "남양주시 화도읍", city_id: 34},
  {title: "남양주시 수동면", city_id: 34},
  {title: "남양주시 호평동", city_id: 34},
  {title: "남양주시 평내동", city_id: 34},
  {title: "남양주시 진전읍", city_id: 35},
  {title: "남양주시 오남읍", city_id: 35},
  {title: "남양주시 별내면", city_id: 35},
  {title: "남양주시 별내동", city_id: 35},
  {title: "남양주시 와부읍", city_id: 36},
  {title: "남양주시 진건읍", city_id: 36},
  {title: "남양주시 조안면", city_id: 36},
  {title: "남양주시 퇴계원면", city_id: 36},
  {title: "남양주시 금곡동", city_id: 36},
  {title: "남양주시 양정동", city_id: 36},
  {title: "남양주시 다산동", city_id: 36},
  {title: "오산시", city_id: 37},
  {title: "시흥시 대야동", city_id: 38},
  {title: "시흥시 신천동", city_id: 38},
  {title: "시흥시 신현동", city_id: 38},
  {title: "시흥시 은행동", city_id: 38},
  {title: "시흥시 매화동", city_id: 38},
  {title: "시흥시 목감동", city_id: 38},
  {title: "시흥시 과림동", city_id: 38},
  {title: "시흥시 연성동", city_id: 38},
  {title: "시흥시 장곡동", city_id: 38},
  {title: "시흥시 능곡동", city_id: 38},
  {title: "시흥시 군자동", city_id: 39},
  {title: "시흥시 월곶동", city_id: 39},
  {title: "시흥시 정왕본동", city_id: 39},
  {title: "시흥시 정왕동", city_id: 39},
  {title: "군포시 군포동", city_id: 40},
  {title: "군포시 산본1동", city_id: 40},
  {title: "군포시 금정동", city_id: 40},
  {title: "군포시 대야동", city_id: 40},
  {title: "군포시 산본2동", city_id: 41},
  {title: "군포시 재궁동", city_id: 41},
  {title: "군포시 오금동", city_id: 41},
  {title: "군포시 수리동", city_id: 41},
  {title: "군포시 궁내동", city_id: 41},
  {title: "군포시 광정동", city_id: 41},
  {title: "하남시", city_id: 42},
  {title: "용인시 처인구", city_id: 43},
  {title: "용인시 기흥구 신갈동", city_id: 44},
  {title: "용인시 기흥구 영덕동", city_id: 44},
  {title: "용인시 기흥구 구갈동", city_id: 44},
  {title: "용인시 기흥구 상갈동", city_id: 44},
  {title: "용인시 기흥구 기흥동", city_id: 44},
  {title: "용인시 기흥구 서농동", city_id: 44},
  {title: "용인시 기흥구 상하동", city_id: 44},
  {title: "용인시 수지구 풍덕천동", city_id: 45},
  {title: "용인시 수지구 신봉동", city_id: 45},
  {title: "용인시 수지구 동천동", city_id: 45},
  {title: "용인시 수지구 상현동", city_id: 45},
  {title: "용인시 수지구 성복동", city_id: 45},
  {title: "용인시 기흥구 구성동", city_id: 46},
  {title: "용인시 기흥구 마북동", city_id: 46},
  {title: "용인시 기흥구 동백동", city_id: 46},
  {title: "용인시 기흥구 보정동", city_id: 46},
  {title: "용인시  수지구 죽전동", city_id: 46},
  {title: "파주시 조리읍", city_id: 47},
  {title: "파주시 광탄면", city_id: 47},
  {title: "파주시 탄현면", city_id: 47},
  {title: "파주시 교하동", city_id: 47},
  {title: "파주시 운정동", city_id: 47},
  {title: "파주시 문산읍", city_id: 48},
  {title: "파주시 법원읍", city_id: 48},
  {title: "파주시 파주읍", city_id: 48},
  {title: "파주시 월롱면", city_id: 48},
  {title: "파주시 적성면", city_id: 48},
  {title: "파주시 파평면", city_id: 48},
  {title: "파주시 장단출장소", city_id: 48},
  {title: "파주시 금촌동", city_id: 48},
  {title: "이천시", city_id: 49},
  {title: "안성시", city_id: 50},
  {title: "김포시 고촌읍", city_id: 51},
  {title: "김포시 김포본동", city_id: 51},
  {title: "김포시 사우동", city_id: 51},
  {title: "김포시 풍무동", city_id: 51},
  {title: "김포시 장기동", city_id: 51},
  {title: "김포시 통진읍", city_id: 52},
  {title: "김포시 양촌읍", city_id: 52},
  {title: "김포시 대곶면", city_id: 52},
  {title: "김포시 월곶면", city_id: 52},
  {title: "김포시 하성면", city_id: 52},
  {title: "김포시 장기본동", city_id: 52},
  {title: "김포시 장기본동", city_id: 52},
  {title: "김포시 구래동", city_id: 52},
  {title: "김포시 운양동", city_id: 52},
  {title: "화성시 우정읍", city_id: 53},
  {title: "화성시 향남읍", city_id: 53},
  {title: "화성시 남양읍", city_id: 53},
  {title: "화서시 매송면", city_id: 53},
  {title: "화성시 매송면", city_id: 53},
  {title: "화성시 비봉면", city_id: 53},
  {title: "화성시 마도면", city_id: 53},
  {title: "화성시 송산면", city_id: 53},
  {title: "화성시 서신면", city_id: 53},
  {title: "화성시 팔탄면", city_id: 53},
  {title: "화성시 장안면", city_id: 53},
  {title: "화성시 양감면", city_id: 53},
  {title: "화성시 정남면", city_id: 53},
  {title: "화성시 동탄면", city_id: 54},
  {title: "화성시 동탄동", city_id: 54},
  {title: "화성시 봉담읍", city_id: 55},
  {title: "화성시 진안동", city_id: 55},
  {title: "화성시 병점동", city_id: 55},
  {title: "화성시 반월동", city_id: 55},
  {title: "화성시 기배동", city_id: 55},
  {title: "화성시 화산동", city_id: 55},
  {title: "광주시 퇴촌면", city_id: 56},
  {title: "광주시 남종면", city_id: 56},
  {title: "광주시 남한산성면", city_id: 56},
  {title: "광주시 경안동", city_id: 56},
  {title: "광주시 송정동", city_id: 56},
  {title: "광주시 광남동", city_id: 56},
  {title: "광주시 오포읍", city_id: 57},
  {title: "광주시 초월읍", city_id: 57},
  {title: "광주시 곤지암읍", city_id: 57},
  {title: "광주시 도척면", city_id: 57},
  {title: "양주시", city_id: 58},
  {title: "포천시", city_id: 59},
  {title: "가평군", city_id: 59},
  {title: "여주시", city_id: 60},
  {title: "양평군", city_id: 60}
])
User.create!([
  {name: "김용균테스트", district_id: 112, phone: "01063271593", birth: 710615, address: "1111-1"},
  {name: "홍길동 ", district_id: 229, phone: "01089563278", birth: 750491, address: "18227"},
  {name: "김연아", district_id: 4, phone: "01023451245", birth: 725840, address: "1232-7"},
  {name: "정우성", district_id: 112, phone: "010456781234", birth: 784127, address: "1526374"},
  {name: "이선영", district_id: 19, phone: "31223213", birth: 3213213, address: "32132"},
  {name: "노종원", district_id: 248, phone: "010-3511-5502", birth: 920802, address: "224-6"},
  {name: "고아라", district_id: 4, phone: "01039752484", birth: 758404, address: "182282"},
  {name: "배범수", district_id: 1, phone: "010-6309-1460", birth: 740520, address: "ㅇㅇㅇ"},
  {name: "오가영", district_id: 179, phone: "01097572928", birth: 771008, address: "하늘마을 102-1801"},
  {name: "오가영", district_id: 179, phone: "01097572928", birth: 771008, address: "하늘마을 102-1801"},
  {name: "김종국", district_id: 204, phone: "01073376225", birth: 690212, address: "998"},
  {name: "윤종암", district_id: 82, phone: "01062112530", birth: 610614, address: "가평군 청평면 경춘로722"},
  {name: "이덕녀", district_id: 196, phone: "01053932174", birth: 601002, address: "수택동 347-10"},
  {name: "윤종암", district_id: 82, phone: "01062112530", birth: 610614, address: "가평군 청평면 경춘로722"},
  {name: "박성원", district_id: 196, phone: "01039552739", birth: 900309, address: "인창동 주공 @608동 1202호"},
  {name: "조석주", district_id: 206, phone: "010-3366-1745", birth: 730119, address: "진건오남로 369-1"},
  {name: "김용균", district_id: 231, phone: "01063271593", birth: 710615, address: "부곡동 1214-6"},
  {name: "진성화", district_id: 203, phone: "01089724848", birth: 630620, address: "청학리 주공아파트711동101호 "},
  {name: "김수기", district_id: 17, phone: "01076454045", birth: 580415, address: "화서1동  82-21"},
  {name: "백수근", district_id: 17, phone: "01033639630", birth: 620202, address: "팔달로 165번길 39 102동 505호(화서동, 벽산아파트)"},
  {name: "김영짐", district_id: 1, phone: "010-2420-7663", birth: 820712, address: ""},
  {name: "박현환", district_id: 30, phone: "010-6297-4911", birth: 590717, address: "벽산한성아파트"},
  {name: "이기현", district_id: 84, phone: "010-5789-9545", birth: 901028, address: "1097-5번지 201호"},
  {name: "유지하", district_id: 204, phone: "01020340579", birth: 800517, address: "한화아파트"},
  {name: "강현철", district_id: 2, phone: "01099024814", birth: 551005, address: "1202-402"},
  {name: "백경하", district_id: 17, phone: "010-5020-9630", birth: 960215, address: "화서동 화서벽산아파트 102동 505호"},
  {name: "백준하", district_id: 17, phone: "010-6520-9630", birth: 980211, address: "화서동 화서벽산아파트 102동 505호"},
  {name: "백민하", district_id: 17, phone: "010-4202-9630", birth: 990225, address: "화서동 화서벽산아파트 102동 505호"},
  {name: "천광필", district_id: 253, phone: "01087024630", birth: 671008, address: "백현주공7단지 2710동 1401호"},
  {name: "천광필", district_id: 253, phone: "01087024630", birth: 671008, address: "백현주공7단지 2710동 1401호"},
  {name: "이종수", district_id: 316, phone: "01045769935", birth: 670429, address: "고암길 조은마을 606-1403"},
  {name: "김요홧", district_id: 2, phone: "01067277747", birth: 760729, address: ""},
  {name: "김경자", district_id: 2, phone: "01081930225", birth: 440207, address: ""},
  {name: "박형암", district_id: 204, phone: "01052870331", birth: 571008, address: "별내3로 4505동205호(우미린아파트)"},
  {name: "이일상", district_id: 200, phone: "010-9689-1043", birth: 581003, address: "593-1 리투안 301호"}
])
